### ISSUE TITLE
    from ..utils.sparse import ll_to_sparse, expand_indptr, _read_file, _read_file_safe   File "/home/joao/Downloads/xclib/xclib/utils/sparse.py", line 1, in <module>     from ._sparse import _rank, read_file, read_file_safe, _topk ModuleNotFoundError: No module named 'xclib.utils._sparse'

### ISSUE THREAD

**Issue by jvitorc17** [kunaldahiya/xctools#1]
Hi
I tried to import data_utils to run the example that is in repository but doesn't work.
` from xclib.data import data_utils`.
The following error appears:
    from ..utils.sparse import ll_to_sparse, expand_indptr, _read_file, _read_file_safe   File "/home/joao/Downloads/xclib/xclib/utils/sparse.py", line 1, in <module>     from ._sparse import _rank, read_file, read_file_safe, _topk ModuleNotFoundError: No module named 'xclib.utils._sparse'

**Comment by kunaldahiya** [comment]
Hi,

Thanks for trying it out. Can you please check the following:
1. Have you installed it as suggested in the readme file?
2. Please make sure that you are not running from xclib directory after installation.

Please let me know if the issue persists.
