### ISSUE TITLE
can't convert df (dict) to np.array?

### ISSUE THREAD

**Issue by cairomo** [kunaldahiya/xctools#15]
in utils/text.py line 577 in _compute_idf
`df = np.array(df, dtype=self.dtype)`

df is created as a dictionary during _create_vocab. why is the dict object df being passed to _compute_idf to be turned into a np array? it raises the error "TypeError: float() argument must be a string or a number, not 'dict'". is the goal to create a csr matrix from the df dict?

is it more valid to do `df = np.array(list(df.values()), dtype=self.dtype)`

**Comment by anshumitts** [comment]
@cairomo Please check the latest commit.
