### ISSUE TITLE
error when run sparse_bow_features_from_raw_data.py

### ISSUE THREAD

**Issue by Yudezhi** [kunaldahiya/xctools#18]
df = np.zeros(vocabulary.__len__ + 1) # +1 for OOV

when run to text.py, get error TypeError: unsupported operand type(s) for +: 'method-wrapper' and 'int'.
Chaned vocabulary.__len__ to vocabulary.__len__() but get another error.

run script:
python sparse_bow_features_from_raw_data.py trn.json.gz tst.json.gz train.txt test.txt

**Comment by kunaldahiya** [comment]
Thanks for the note. Fixed in latest commit.

**Comment by Yudezhi** [comment]
Thanks. Things goes well now.
