### ISSUE TITLE
What is the feature value ?

### ISSUE THREAD

**Issue by jellchou** [kunaldahiya/xctools#19]
As we know, each datapoint is like this: 
label1, label2  ft1:ft1_val
how could you get the feature value,  let us take LF-AmazonTitles-131K as an example?

**Comment by kunaldahiya** [comment]
This is typically tf-idf value for a document-feature pair. You can refer to [this example](https://github.com/kunaldahiya/pyxclib/blob/master/xclib/examples/sparse_bow_features_from_raw_data.py) to get a sense of how to create sparse features. I'll be happy to clarify is something is still unclear.

**Comment by jellchou** [comment]
> 

Thanks, got it!
