### ISSUE TITLE
Xf.txt and Yf.txt files

### ISSUE THREAD

**Issue by jellchou** [kunaldahiya/xctools#20]
How does the Xf.txt， Yf.txt file generated in LF-AmazonTitles-131K, did you known?

**Comment by kunaldahiya** [comment]
Xf.txt just contains the tokens in the vocabulary (one token per line). Yf.txt is the features for labels created in the same way as trn_X_Xf.txt for train dataset.

**Comment by jellchou** [comment]
> Xf.txt just contains the tokens in the vocabulary (one token per line). Yf.txt is the features for labels created in the same way as trn_X_Xf.txt for train dataset.

I see, and does the labels in some specific order? how does the features correspond to  the label.

**Comment by jellchou** [comment]
> Xf.txt just contains the tokens in the vocabulary (one token per line). Yf.txt is the features for labels created in the same way as trn_X_Xf.txt for train dataset.

I found that  count of Yf.txt  lines is equal to label_raw_ids.txt.
What is the input of the generation code for Yf.txt, is it label_raw_ids.txt?

**Comment by kunaldahiya** [comment]
No, each label has text associated with it - so that text can be used to create tf-idf features much like train and test data. Yf.txt contains those features. 

See the 'lbl.json.gz' file for the label text ('label_raw_ids.txt' should be used to find the mapping between raw text and the label id in the dataset).

**Comment by jellchou** [comment]
> No, each label has text associated with it - so that text can be used to create tf-idf features much like train and test data. Yf.txt contains those features.
> 
> See the 'lbl.json.gz' file for the label text ('label_raw_ids.txt' should be used to find the mapping between raw text and the label id in the dataset).

A clear explanation, thx!

**Comment by jellchou** [comment]
I checked the lbl.json.gz,  if confused me that `title` is the label text as you said. And what `target_ind` is in trn.json or tst.json? Is it label index?
