### ISSUE TITLE
How to convert from Raw text data to the Parabel sparse matrix text format using Python?

### ISSUE THREAD

**Issue by NIkhilbadveli** [kunaldahiya/xctools#23]
I'm looking to train a XML classifier on the [PubMed ](https://www.kaggle.com/datasets/hsrobo/titlebased-semantic-subject-indexing?select=pubmed.csv) dataset. I found out after some research that Parabel is the fastest.

So far, I was able to make it work on toy dataset Eur-Lex. Now, I'm trying to with the above mentioned dataset. So, I need to convert according to the format required by the Parabel C++ code.

The format is explained [here](https://drive.google.com/file/d/1u7YibXAC_Wz1RDehN1KjB5vu21zUnapV/view). I could generate it by writing custom code but I want to know if there is already some script for this.

Thanks.

**Comment by kunaldahiya** [comment]
Hi

Do you mean the code for converting raw-text to sparse BoW features or writing the features & labels in the expected format? Please see [this example](https://github.com/kunaldahiya/pyxclib/blob/master/xclib/examples/sparse_bow_features_from_raw_data.py) which gives brief overview of the process.

**Comment by NIkhilbadveli** [comment]
Actually, I think it's both. I want to convert raw text into the train and test feature and label .txt files as expected by the Parabel binaries.

Update:-
After checking the example you mentioned I understood that it's converting raw text to BoW features along with saving them into train and test .txt files.

And that data_utils file has some useful functions to get what I want. I'll try doing it using these and if I face any issues I'll let you know.

Thanks for the quick response.

**Comment by kunaldahiya** [comment]
Right. You may need to change the read function as per your input format.

**Comment by NIkhilbadveli** [comment]
I'm trying to install it using setup.py, but it's throwing this error. I'm on Windows 11. And can I install this somehow using pip? I need the package inside a venv.

**error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2**

**Comment by kunaldahiya** [comment]
I haven't been able to find the time to set up the pip. On Windows you'll need to do the following:

- Install VS 2022 Build Tools and Windows xx SDK. Otherwise it'll throw the error you mentioned and error related to missing 'io.h'.
- Change the data type of indptr and indices [here](https://github.com/kunaldahiya/pyxclib/blob/13c7976a202b113f56c59be7b956f95d47704f8e/xclib/utils/sparse.py#L257) and [here](https://github.com/kunaldahiya/pyxclib/blob/13c7976a202b113f56c59be7b956f95d47704f8e/xclib/utils/sparse.py#L285) to np.int_. There is some weird issue in converting long to int64 on Windows - it works fine on Linux.

**Comment by NIkhilbadveli** [comment]
Hi, I got it working now. Thanks for the help. I was able to convert the data as needed by the Parabel binaries but when it's throwing error when I tried to train with [this data](https://drive.google.com/file/d/12vofyrcYp1xpSoGsVk9UWKXLo7dfX9_e/view?usp=sharing).

**Error**:- Assertion failed: inds.size()==vals.size(), file ..\Tools\c++\mat.h, line 198

Is this line trying to check if the indices and the values match?

**Comment by kunaldahiya** [comment]
It seems like it is trying to check the size of ind and vals. You should check with Parabel's author regarding this.
