### ISSUE TITLE
I feel confused about data_utils.read_sparse_file function

### ISSUE THREAD

**Issue by xuehuachunsheng** [kunaldahiya/xctools#24]
When I run 
`true_labels = data_utils.read_sparse_file('Sandbox/Data/EUR-Lex/tst_X_Y.txt')`
It raise an exception that `ValueError: buffer size must be a multiple of element size` from sparse.py line 257, 
i.e., `indices = np.frombuffer(ind, np.int64)`
I see that `ind` is an array that with typecode = 'l', it seems that the each element in `ind` takes 4 bytes, according to `https://docs.python.org/3/library/array.html`.

So I am confused that why loading frombuffer with dtype np.int64? 

My machine is 64bit OS.
Python is the version 3.8.8.

**Comment by kunaldahiya** [comment]
Hi

Are you running it on Windows?

**Comment by xuehuachunsheng** [comment]
Yes. So where is the problem?

**Comment by kunaldahiya** [comment]
The issue is Windows specific. Please refer to the [solution mentioned here](https://github.com/kunaldahiya/pyxclib/issues/23#issuecomment-1198409035).
