### ISSUE TITLE
Why propensity scored precision can be less than precision?

### ISSUE THREAD

**Issue by Odaimoko** [kunaldahiya/xctools#3]
As the formula suggests, `1/p_l=1+C(N_l+B)^(-A)` should be always larger than one. So `psp@k = 1/k * \sum  y_l/p_l` should be larger than `p@k = 1/k \sum y_l`. Thus I am confused by the results shown on [XML repo website](http://manikvarma.org/downloads/XC/XMLRepository.html), in which most of the time psp numbers are smaller.

**Comment by anshumitts** [comment]
Hi, psp@k numbers must be normalized by highest psp any model can achieve for top k prediction. Hence, these numbers are often less

**Comment by Odaimoko** [comment]
I am confused by `highest psp any model can achieve for top k prediction`. Does this mean the psp@k of a model which predicts all result correctly, i.e. p@k=100%? Can you give a formula for this?

**Comment by anshumitts** [comment]
consider test point (doc) with ground truth as 1,2,3,4,5,6 with inverse 
propensity scores as 4,5,6,1,2,3. Now, for maximum psp@k(k=3)_max any 
model can achieve is (6+5+4)/3 = 15/3 = 5. and let say top 3 prediction 
of your model is 4, 5 , 6 which have psp@k_model score of (1+2+3)/3 = 2. 
Now normalized psp or simply psp = psp@k_model/psp@k_max = 2/5 = 0.4 or 
40%. Here, p@3 is 100% but still psp@3 is less than p@3.

Please let us know if it clears your doubt.

**Comment by Odaimoko** [comment]
Yes it does. Thank you very much!

**Comment by dalgu90** [comment]
Could you help me find the reason/reference for normalizing PSP@k to the maximum possible value?
I understood the pros of doing this, including scaling to 0~1 and making the measure comparable among different datasets, but I still want to know a more clear reference on this.
I've read a few papers, including Jain et al. 2016 (Extreme Multi-label Loss Functions for Recommendation, Tagging, Ranking & Other Missing Label Applications), but I couldn't find it yet.

Sorry for asking in an old thread. Thank you very much!
