### ISSUE TITLE
Discrepancy in the Order of Returned Variables from baseline_test Function

### ISSUE THREAD

**Issue by kennishida17** [kunaldahiya/xctools#32]
## Discrepancy in the Order of Returned Variables from baseline_test Function

Firstly, I apologize if my explanation is unclear as I'm not very experienced with using GitHub.

I noticed a small discrepancy in the return order of the variables from a function. 

The function returns the values in the following order:

https://github.com/kennishida17/Learning-with-Holographic-Reduced-Representations/blob/ce3cb8fc4c63b16f41fc41d8788503ebe146c73c/lib/model.py#L175C1-L177C51

```python
else:
        return total_loss/num_itr, total_f1/num_itr, total_pr/num_itr, total_rec/num_itr
```

However, when receiving the output of the function, it's assumed to be in this order:

https://github.com/kennishida17/Learning-with-Holographic-Reduced-Representations/blob/ce3cb8fc4c63b16f41fc41d8788503ebe146c73c/run_classifier.py#L222

```python
val_loss, pr, rec, f1 = baseline_test(model, device, val_loader)
```

## Proposed Change

I suggest adjusting the return order in the baseline_test function to match the order when receiving the output. The correct order should be:
```python
return total_loss/num_itr, total_pr/num_itr, total_rec/num_itr, total_f1/num_itr

**Comment by kunaldahiya** [comment]
Hi

I am confused. How is this relevant to pyxclib?

**Comment by kennishida17** [comment]
@kunaldahiya 


I'm sorry, I mistakenly sent this to you when I meant to comment on another GitHub code related to pyxclib.

I apologize for any confusion caused.
