### ISSUE TITLE
PSP@k and PSnDCG@k

### ISSUE THREAD

**Issue by celsofranssa** [kunaldahiya/xctools#35]
Evaluating the definition of `PSP` and `PSnDCG` (shown below), these metrics can assume values greater than `1.0` since propensity is between 0 and 1.

![image](https://github.com/kunaldahiya/pyxclib/assets/11181748/5a0fdf83-6757-439f-bce1-b1f2ff7044f6)

So,  do you happen to have any test cases for these metrics that would allow me to verify the correctness of my implementation?

**Comment by kunaldahiya** [comment]
Thanks for your interest.

[score.txt](https://github.com/kunaldahiya/pyxclib/files/13516260/score.txt)
[tst_X_Y.txt](https://github.com/kunaldahiya/pyxclib/files/13516262/tst_X_Y.txt)

Sending ground truth and score matrix for EURLex-4K dataset. You can use it to compare your implementation against ours.

**Comment by celsofranssa** [comment]
Hello @kunaldahiya,
thanks for sharing these files. However, I am facing the following errors after the pyxclib installation:

```python
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-8-3987c0525a05>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from xclib.data import data_utils
      2 import xclib.evaluation.xc_metrics as xc_metrics

1 frames
[/content/pyxclib/xclib/utils/sparse.py](https://localhost:8080/#) in <module>
----> 1 from ._sparse import _rank, read_file, read_file_safe, _topk
      2 from scipy.sparse import csr_matrix, isspmatrix, coo_matrix
      3 import numpy as np
      4 import warnings
      5 from sklearn.preprocessing import normalize as sk_normalize

ModuleNotFoundError: No module named 'xclib.utils._sparse'
```

You can check the complete installation output in this [Google Colab notebook](https://colab.research.google.com/drive/1CPA0NDFMVsVuHTlFDQky_qRXXV7omvsf?usp=sharing).

**Comment by celsofranssa** [comment]
I was able to resolve by changing the Python version to `3.8.10` and using the following dependencies versions:
```python
Cython==0.29.30
nmslib==2.1.1
numba==0.58.1
numpy==1.23.5
pandas==2.0.3
scikit-learn==1.3.2
scipy==1.10.1
```

**Comment by kunaldahiya** [comment]
This issue typically happens when one tries to load stuff from the original directory itself.
