### ISSUE TITLE
Some questions about the PSP@k and PSnDCG@k

### ISSUE THREAD

**Issue by celsofranssa** [kunaldahiya/xctools#36]
Evaluating the results when running `pyxclib` metrics, certain uncertainties surfaced:

1. Could you clarify the definition of propensity scores utilized for precision and nDCG?
2. What are the upper and lower limits of these metrics?
3. Under what circumstances do propensity-scored metrics reach their maximum and minimum values?

**Comment by shikharmn** [comment]
Hi, please refer to [this article](http://manikvarma.org/downloads/XC/XMLRepository.html), particularly the **Performance Metrics and Evaluation Protocols** section for details.
