### ISSUE TITLE
Might be a bug when calculating precision

### ISSUE THREAD

**Issue by Odaimoko** [kunaldahiya/xctools#5]
In methods `precision`([link](https://github.com/kunaldahiya/pyxclib/blob/e1100a4013ad9edbfde1524093916a4d870d9a3e/xclib/evaluation/xc_metrics.py#L202)), the `indices` returned by `_setup_metric` is the indices of top k labels, with scores sorted ascendingly. But when calculating [precision@k](https://github.com/kunaldahiya/pyxclib/blob/e1100a4013ad9edbfde1524093916a4d870d9a3e/xclib/evaluation/xc_metrics.py#L239), we want to use cumsum when scores in `eval_flags` are sorted descendingly. The same is to `psprecision` since it uses `precision` as a subroutine. 

I just add change `indices` to `indices[:, ::-1]` in [_get_top_k](https://github.com/kunaldahiya/pyxclib/blob/e1100a4013ad9edbfde1524093916a4d870d9a3e/xclib/evaluation/xc_metrics.py#L117). Guess it is just a workaround.

**Comment by anshumitts** [comment]
@Odaimoko Thank you for pointing this out. Please let us know if the issue has been resolved.
