### ISSUE TITLE
Efficient utils.sparse.retain_topk

### ISSUE THREAD

**Issue by nilesh2797** [kunaldahiya/xctools#6]
Current code of retain_topk does : `X[ranks > k] = 0.0; X.eliminate_zeros()`.

Ther first operation seems very expensive and in my experiments i've seen that doing something like `X.data[np.where(ranks.data > k)[0]] = 0.0` is much more efficient than `X[ranks > k] = 0.0`. Can you please check this

**Comment by kunaldahiya** [comment]
Done. Take a look and let me know.

**Comment by nilesh2797** [comment]
Yes, this looks good to me.
