### ISSUE TITLE
what is the A and B for xc_metrics.compute_inv_propesity for AmazonCat 13K dataset?

### ISSUE THREAD

**Issue by DanqingZ** [kunaldahiya/xctools#7]
https://github.com/kunaldahiya/pyxclib/blob/master/xclib/evaluation/xc_metrics.py#L128-L137

In the script, it is said: A=0.6, B=2.6 for Amazon. But there are multiple Amazon datasets, for example AmazonCat 13K dataset ,Amazon 670k and Amazon 3M. Should we use the same A and B for calculating the propensity score for all the Amazon datasets? Thanks.

**Comment by anshumitts** [comment]
yes you should
[UPDATE]
For AmazonCat-13K use 0.55 and 1.5 respectively

**Comment by DanqingZ** [comment]
Thanks.
